### ISSUE TITLE
Api occasionally returns empty array

### ISSUE THREAD

**Issue by mjdierkes** [SumitNalavade/GradualGrades_API#14]
It would be nice if AWS could somehow ping the Heroku to keep the server active. 

But if that is too difficult, maybe add an error code for Heroku booting up? 
I need to somehow make sure the data isn't empty so my code doesn't crash.

```swift
let loadedSATs: UpcomingSATs = try await gradeService.fetchData(from: .satDates)
nextSAT = loadedSATs.liveDates[0]
```

**Comment by SumitNalavade** [comment]
I setup kaffine to ping the server every 30 minutes so it won’t sleep except between 12:00AM and 6:00AM

https://kaffeine.herokuapp.com/

**Comment by mjdierkes** [comment]
Awesome!!!! That's so cool
