### ISSUE TITLE
John Doe has different key value pairs

### ISSUE THREAD

**Issue by mjdierkes** [SumitNalavade/GradualGrades_API#9]
`// 20220120083025
// http://gradualgrades-env.eba-dkw3kc3t.us-east-2.elasticbeanstalk.com/students/info/john/doe

{
  "studentBirthDate": "12/24/2003",
  "studentBuilding": "Heritage High School",
  "studentGrade": "12",
  "studentID": "123456",
  "studentName": "Jonh Doe"
}`

**Comment by SumitNalavade** [comment]
Resolved
